Repository ajounice/momentrip_frontend, pull requests merged in 2022-12, with the labels that each got.

#90 feat: mypage-setting: 회원탈퇴
  src/index.tsx
  src/pages/ProfileSettingPage.tsx
  src/pages/mypage/ChangePasswordPage.tsx
  src/pages/mypage/MyPage.tsx
  src/pages/mypage/SettingPage.tsx
Labels: style-bug, feature, refactor, finish(pr), code-review

#91 feat: mypage-setting change password
  src/index.tsx
  src/pages/mypage/ChangePassword.tsx
Labels: refactor, finish(pr)

#96 issues/65
  src/components/View/ShortForm.tsx
  src/styles/components/Modal/Vertical/TourInfo.css
Labels: style-bug, style, finish(pr)

#94 fix(search): 인기태그로 검색 진입 시 검색창에 키워드 보이도록 변경
  src/App.tsx
  src/components/Search/SearchAfter.tsx
  src/components/Search/SearchBar.tsx
  src/components/Search/SearchBefore.tsx
  src/index.tsx
  src/pages/SearchPage.tsx
  src/pages/search/SearchPage.tsx
Labels: bug, code-review

#99 Refactor/api response
  src/components/Modal/Vertical/Comment.tsx
  src/components/Navigation/VerticalNavigation.tsx
  src/components/Search/SearchAfter.tsx
  src/components/Search/SearchBar.tsx
  src/components/View/ShortForm.tsx
  src/components/common/Input.tsx
  src/components/common/ProfileInSF.tsx
  src/pages/HomePage.tsx
  src/pages/mypage/ChangePassword.tsx
  src/pages/mypage/ChangePasswordPage.tsx
  src/pages/search/SearchPage.tsx
  src/styles/pages/mypage/Setting.css
Labels: feature, refactor, finish(pr)
